"""
Реестр сборки армий (Ростер) фракции 'Паства метеорита'.
Объединяет UnitArchetype + Weapon + Armor + Accessory в готовую карточку найма.
"""

from typing import Any

from src.back.gamedata.congregation_of_the_meteorite.common import (
    CotmAccessoryId,
    CotmArmorId,
    CotmRosterId,
    CotmUnitId,
    CotmWeaponId,
)

_FACTION = "congregation_of_the_meteorite"

ROSTER_LIST: dict[str, dict[str, Any]] = {
    CotmRosterId.ROSTER_LOOTERS.value: {
        "id": CotmRosterId.ROSTER_LOOTERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.GOBLIN_LOOTERS_00.value,
        "weapon_id": CotmWeaponId.RUSTY_KNIVES_00.value,
        "armor_id": CotmArmorId.CULTIST_RAGS_00.value,
        "accessory_id": CotmAccessoryId.BONE_AMULET_00.value,
        "cost_gold": 1.0,
        "cost_material": 3.0,
    },
    CotmRosterId.ROSTER_NECROMANCERS.value: {
        "id": CotmRosterId.ROSTER_NECROMANCERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.NECROMANCERS_00.value,
        "weapon_id": CotmWeaponId.RITUAL_SICKLES_00.value,
        "armor_id": CotmArmorId.FLAYED_SKIN_00.value,
        "accessory_id": None,
        "cost_gold": 4.0,
        "cost_material": 5.0,
    },
    CotmRosterId.ROSTER_ZOMBIES.value: {
        "id": CotmRosterId.ROSTER_ZOMBIES.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.ZOMBIE_HORDE_01.value,
        "weapon_id": CotmWeaponId.ROTTEN_CLAWS_01.value,
        "armor_id": CotmArmorId.FUSED_FLESH_01.value,
        "accessory_id": CotmAccessoryId.RUSTY_BUCKLER_01.value,
        "cost_gold": 0.0,  # Нанимаются чисто за трупы/материалы
        "cost_material": 10.0,
    },
    CotmRosterId.ROSTER_DEMONS.value: {
        "id": CotmRosterId.ROSTER_DEMONS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.LESSER_DEMONS_01.value,
        "weapon_id": CotmWeaponId.ROTTEN_CLAWS_01.value,
        "armor_id": CotmArmorId.FUSED_FLESH_01.value,
        "accessory_id": CotmAccessoryId.BLOOD_FLASK_01.value,
        "cost_gold": 5.0,
        "cost_material": 12.0,
    },
    CotmRosterId.ROSTER_GLADIATORS.value: {
        "id": CotmRosterId.ROSTER_GLADIATORS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.ORC_GLADIATORS_02.value,
        "weapon_id": CotmWeaponId.REAPER_SCYTHES_02.value,
        "armor_id": CotmArmorId.GLADIATOR_CARAPACE_02.value,
        "accessory_id": CotmAccessoryId.SPIKED_SHIELD_02.value,
        "cost_gold": 8.0,
        "cost_material": 15.0,
    },
    CotmRosterId.ROSTER_DARK_ARMS.value: {
        "id": CotmRosterId.ROSTER_DARK_ARMS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.DARK_MEN_AT_ARMS_02.value,
        "weapon_id": CotmWeaponId.CORRUPTED_FALCHIONS_02.value,
        "armor_id": CotmArmorId.CURSED_PLATE_02.value,
        "accessory_id": CotmAccessoryId.DARK_WHISPER_SCROLL_02.value,
        "cost_gold": 12.0,
        "cost_material": 18.0,
    },
    CotmRosterId.ROSTER_GHOSTS.value: {
        "id": CotmRosterId.ROSTER_GHOSTS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.GHOSTS_02.value,
        "weapon_id": CotmWeaponId.RUSTY_KNIVES_00.value,
        "armor_id": CotmArmorId.SHADOW_CLOAKS_03.value,
        "accessory_id": CotmAccessoryId.DARK_WHISPER_SCROLL_02.value,
        "cost_gold": 15.0,
        "cost_material": 20.0,
    },
    CotmRosterId.ROSTER_WEREWOLVES.value: {
        "id": CotmRosterId.ROSTER_WEREWOLVES.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.WEREWOLVES_03.value,
        "weapon_id": CotmWeaponId.ROTTEN_CLAWS_01.value,
        "armor_id": CotmArmorId.FUSED_FLESH_01.value,
        "accessory_id": CotmAccessoryId.BLOOD_FLASK_01.value,
        "cost_gold": 10.0,
        "cost_material": 30.0,
    },
    CotmRosterId.ROSTER_BLOODLETTERS.value: {
        "id": CotmRosterId.ROSTER_BLOODLETTERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.ELF_BLOODLETTERS_03.value,
        "weapon_id": CotmWeaponId.RESONITE_DAGGERS_03.value,
        "armor_id": CotmArmorId.SHADOW_CLOAKS_03.value,
        "accessory_id": CotmAccessoryId.RITUAL_DAGGER_03.value,
        "cost_gold": 25.0,
        "cost_material": 35.0,
    },
    CotmRosterId.ROSTER_BLOOD_MAGES.value: {
        "id": CotmRosterId.ROSTER_BLOOD_MAGES.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.BLOODLETTING_MAGE_03.value,
        "weapon_id": CotmWeaponId.RITUAL_SICKLES_00.value,
        "armor_id": CotmArmorId.FLAYED_SKIN_00.value,
        "accessory_id": CotmAccessoryId.PROGENITOR_AMULETS_03.value,
        "cost_gold": 30.0,
        "cost_material": 25.0,
    },
    CotmRosterId.ROSTER_BOMBERS.value: {
        "id": CotmRosterId.ROSTER_BOMBERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.BOMBERS_03.value,
        "weapon_id": CotmWeaponId.RUSTY_KNIVES_00.value,  # Основной урон они наносят абилками / самоподрывом
        "armor_id": CotmArmorId.CULTIST_RAGS_00.value,
        "accessory_id": None,
        "cost_gold": 15.0,
        "cost_material": 20.0,
    },
    CotmRosterId.ROSTER_MUMMIES.value: {
        "id": CotmRosterId.ROSTER_MUMMIES.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.MUMMY_SUMMONERS_04.value,
        "weapon_id": CotmWeaponId.NECROSIS_STAFF_04.value,
        "armor_id": CotmArmorId.EMBALMER_SHROUD_04.value,
        "accessory_id": CotmAccessoryId.CANOPIC_JAR_04.value,
        "cost_gold": 40.0,
        "cost_material": 80.0,
    },
    CotmRosterId.ROSTER_DRAGON.value: {
        "id": CotmRosterId.ROSTER_DRAGON.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.GREEDY_DRAGON_05.value,
        "weapon_id": CotmWeaponId.PROGENITOR_FLAME_05.value,
        "armor_id": CotmArmorId.FUSED_FLESH_01.value,
        "accessory_id": CotmAccessoryId.GOLDEN_IDOL_05.value,
        "cost_gold": 150.0,  # Огромная разовая цена
        "cost_material": 100.0,
    },
    CotmRosterId.ROSTER_RIDERS.value: {
        "id": CotmRosterId.ROSTER_RIDERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.IMMORTAL_RIDERS_05.value,
        "weapon_id": CotmWeaponId.GHOST_SPEARS_05.value,
        "armor_id": CotmArmorId.ETHEREAL_ARMOR_05.value,
        "accessory_id": CotmAccessoryId.DARK_WHISPER_SCROLL_02.value,
        "cost_gold": 80.0,
        "cost_material": 150.0,
    },
    CotmRosterId.ROSTER_HARBINGERS.value: {
        "id": CotmRosterId.ROSTER_HARBINGERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": CotmUnitId.DOOM_HARBINGERS_06.value,
        "weapon_id": CotmWeaponId.PROGENITOR_FLAME_05.value,
        "armor_id": CotmArmorId.ETHEREAL_ARMOR_05.value,
        "accessory_id": CotmAccessoryId.PROGENITOR_AMULETS_03.value,
        "cost_gold": 300.0,
        "cost_material": 500.0,
    },
}
