"""
Реестр аксессуаров фракции 'Паства метеорита'.
"""

from typing import Any

from src.back.l01_domain.army.constants import (
    AccessoryCategory,
    EquipmentSlot,
    EquipmentTag,
)
from src.back.l01_domain.army.models.card.equipment import EquipmentStats
from src.back.gamedata.congregation_of_the_meteorite.common import CotmAccessoryId

_SLOT = EquipmentSlot.ACCESSORY

ACCESSORIES_LIST: dict[str, dict[str, Any]] = {
    CotmAccessoryId.BONE_AMULET_00.value: {
        "id": CotmAccessoryId.BONE_AMULET_00.value,
        "name": "Амулет из костей",
        "lore": "Примитивная поделка, пропитанная легкой магией. Придает мародерам неестественную резвость.",
        "slot": _SLOT,
        "category": AccessoryCategory.RELIC,
        "tier": 0,
        "cost_gold": 0.5,
        "cost_material": 1.0,
        "stats": EquipmentStats(initiative_modifier=2),
    },
    CotmAccessoryId.BLOOD_FLASK_01.value: {
        "id": CotmAccessoryId.BLOOD_FLASK_01.value,
        "name": "Флакон с кровью",
        "lore": "Запас свежей крови для подпитки мутаций и поддержания жизни в гниющих телах.",
        "slot": _SLOT,
        "category": AccessoryCategory.POTION,
        "tier": 1,
        "cost_gold": 2.0,
        "cost_material": 1.0,
        "stats": EquipmentStats(),
        "special_rules": "вливание: может быть израсходован один раз за бой, чтобы восстановить 20% ХП отряда.",
    },
    CotmAccessoryId.RUSTY_BUCKLER_01.value: {
        "id": CotmAccessoryId.RUSTY_BUCKLER_01.value,
        "name": "Ржавый баклер",
        "lore": "Крошечный щит. Защищает плохо, но лучше, чем ничего.",
        "slot": _SLOT,
        "category": AccessoryCategory.SHIELD,
        "tier": 1,
        "tags": {EquipmentTag.ONE_HANDED},
        "cost_gold": 1.0,
        "cost_material": 2.0,
        "stats": EquipmentStats(armor_bonus=2.0),
        "special_rules": "отражение: блокирует 20% урона от немагических стрел.",
    },
    CotmAccessoryId.DARK_WHISPER_SCROLL_02.value: {
        "id": CotmAccessoryId.DARK_WHISPER_SCROLL_02.value,
        "name": "Свиток темного шепота",
        "lore": "Человеческая кожа с начертанными на ней безумными откровениями Прародителя.",
        "slot": _SLOT,
        "category": AccessoryCategory.RELIC,
        "tier": 2,
        "tags": {EquipmentTag.CURSED},
        "cost_gold": 5.0,
        "cost_material": 4.0,
        "stats": EquipmentStats(),
        "special_rules": "шепот бездны: один раз за бой отряд может наложить эффект 'Страх' на соседний гекс противника.",
    },
    CotmAccessoryId.SPIKED_SHIELD_02.value: {
        "id": CotmAccessoryId.SPIKED_SHIELD_02.value,
        "name": "Шипованный щит",
        "lore": "Тяжелый щит, усеянный ржавыми гвоздями и осколками костей. Враг ранит сам себя, пытаясь пробить защиту.",
        "slot": _SLOT,
        "category": AccessoryCategory.SHIELD,
        "tier": 2,
        "tags": {EquipmentTag.ONE_HANDED, EquipmentTag.HEAVY},
        "cost_gold": 3.0,
        "cost_material": 6.0,
        "stats": EquipmentStats(armor_bonus=4.0, speed_modifier=-0.05),
        "special_rules": "шипы: наносит ответный физический урон при атаке врага в ближнем бою.",
    },
    CotmAccessoryId.PROGENITOR_AMULETS_03.value: {
        "id": CotmAccessoryId.PROGENITOR_AMULETS_03.value,
        "name": "Амулеты Прародителя",
        "lore": "Реликвия истинных верующих. Если они погибают, их братья видят в этом священную жертву.",
        "slot": _SLOT,
        "category": AccessoryCategory.RELIC,
        "tier": 3,
        "cost_gold": 8.0,
        "cost_material": 8.0,
        "stats": EquipmentStats(),
        "special_rules": "мученичество: если этот отряд полностью погибает, все союзники в радиусе 3 гексов получают +20 к морали.",
    },
    CotmAccessoryId.RITUAL_DAGGER_03.value: {
        "id": CotmAccessoryId.RITUAL_DAGGER_03.value,
        "name": "Кинжал ритуального самоубийства",
        "lore": "Сектанты не боятся смерти. Этим кинжалом они вскрывают себе артерии, высвобождая магию крови.",
        "slot": _SLOT,
        "category": AccessoryCategory.MISC,
        "tier": 3,
        "tags": {EquipmentTag.ONE_HANDED, EquipmentTag.CURSED},
        "cost_gold": 10.0,
        "cost_material": 5.0,
        "stats": EquipmentStats(damage=2.0),
        "special_rules": "кровавая жертва: разблокирует команду самоуничтожения. Отряд погибает, накладывая колоссальные баффы на союзников в зоне.",
    },
    CotmAccessoryId.CANOPIC_JAR_04.value: {
        "id": CotmAccessoryId.CANOPIC_JAR_04.value,
        "name": "Канопа с прахом",
        "lore": "Урна, наполненная токсичным пеплом и гнилью. Призыватели мумий разбивают их о землю перед атакой.",
        "slot": _SLOT,
        "category": AccessoryCategory.POTION,
        "tier": 4,
        "tags": {EquipmentTag.CURSED},
        "cost_gold": 12.0,
        "cost_material": 15.0,
        "stats": EquipmentStats(),
        "special_rules": "трупный яд: добавляет всем атакам шанс заразить цель трупным ядом (постоянный урон здоровью и морали).",
    },
    CotmAccessoryId.GOLDEN_IDOL_05.value: {
        "id": CotmAccessoryId.GOLDEN_IDOL_05.value,
        "name": "Золотой идол жадности",
        "lore": "Отвратительная статуэтка, притягивающая алчное внимание дракона, успокаивая его голод.",
        "slot": _SLOT,
        "category": AccessoryCategory.RELIC,
        "tier": 5,
        "cost_gold": 50.0,
        "cost_material": 10.0,
        "stats": EquipmentStats(),
        "special_rules": "смирение алчности: снижает стоимость содержания Алчного дракона на 10 золота за каждый стратегический такт.",
    },
}
