"""
Реестр аксессуаров фракции людей.
"""

from typing import Any

from src.back.l01_domain.army.constants import (
    AccessoryCategory,
    EquipmentSlot,
    EquipmentTag,
)
from src.back.l01_domain.army.models.card.equipment import EquipmentStats
from src.back.gamedata.humans.common import HumanAccessoryId

_SLOT = EquipmentSlot.ACCESSORY

ACCESSORIES_LIST: dict[str, dict[str, Any]] = {
    HumanAccessoryId.FLAMING_TORCHES_00.value: {
        "id": HumanAccessoryId.FLAMING_TORCHES_00.value,
        "name": "Пылающие факелы",
        "lore": "Самое доступное освещение в эпоху Долгой зимы. Также отлично поджигает сухую траву.",
        "slot": _SLOT,
        "category": AccessoryCategory.MISC,
        "tier": 0,
        "tags": {EquipmentTag.FLAMMABLE, EquipmentTag.ONE_HANDED},
        "cost_gold": 0.0,
        "cost_material": 0.5,
        "stats": EquipmentStats(damage=1.0),
        "special_rules": "Поджог: позволяет поджигать соседние лесные гексы на поле боя.",
    },
    HumanAccessoryId.PAVISE_SHIELD_01.value: {
        "id": HumanAccessoryId.PAVISE_SHIELD_01.value,
        "name": "Деревянная павеза",
        "lore": "Тяжелый ростовой щит, который арбалетчики втыкают в землю перед собой во время перезарядки.",
        "slot": _SLOT,
        "category": AccessoryCategory.SHIELD,
        "tier": 1,
        "tags": {EquipmentTag.ONE_HANDED, EquipmentTag.HEAVY},
        "cost_gold": 1.0,
        "cost_material": 3.0,
        "stats": EquipmentStats(
            armor_bonus=2.0,
            speed_modifier=-0.05,
        ),
        "special_rules": "Глухое укрытие: если отряд стоит в темпе обороны, он полностью поглощает урон от первой дальней атаки.",
    },
    HumanAccessoryId.HUNTING_HORN_01.value: {
        "id": HumanAccessoryId.HUNTING_HORN_01.value,
        "name": "Охотничий горн",
        "lore": "Звук этого рога сводит с ума боевых псов, заставляя их рвать поводки.",
        "slot": _SLOT,
        "category": AccessoryCategory.INSTRUMENT,
        "tier": 1,
        "cost_gold": 1.5,
        "cost_material": 1.0,
        "stats": EquipmentStats(initiative_modifier=2),
        "special_rules": "Псовая охота: увеличивает дальность и урон натиска для отрядов с боевыми животными.",
    },
    HumanAccessoryId.POWDER_BANDOLIER_02.value: {
        "id": HumanAccessoryId.POWDER_BANDOLIER_02.value,
        "name": "Пороховая бандольера",
        "lore": "Деревянные мерки с точно отмеренными зарядами сухого пороха. Ускоряют перезарядку и спасают от влаги.",
        "slot": _SLOT,
        "category": AccessoryCategory.AMMUNITION,
        "tier": 2,
        "cost_gold": 3.0,
        "cost_material": 2.0,
        "stats": EquipmentStats(initiative_modifier=1),
        "special_rules": "Защита от влаги: убирает штраф на шанс осечки во время дождя.",
    },
    HumanAccessoryId.SURGICAL_SAWS_02.value: {
        "id": HumanAccessoryId.SURGICAL_SAWS_02.value,
        "name": "Хирургические пилы",
        "lore": "Чистые и наточенные инструменты полевых лекарей. Ужасают новобранцев, но спасают жизни.",
        "slot": _SLOT,
        "category": AccessoryCategory.MISC,
        "tier": 2,
        "cost_gold": 4.0,
        "cost_material": 3.0,
        "stats": EquipmentStats(),
        "special_rules": "Полевая хирургия: увеличивает эффективность воскрешения павших от полевых госпиталей.",
    },
    HumanAccessoryId.HOLY_WATER_FLASK_03.value: {
        "id": HumanAccessoryId.HOLY_WATER_FLASK_03.value,
        "name": "Флакон со святой водой",
        "lore": "Вода, очищенная от следов резонита. Жжет плоть мутантов словно кислота.",
        "slot": _SLOT,
        "category": AccessoryCategory.POTION,
        "tier": 3,
        "tags": {EquipmentTag.ONE_HANDED, EquipmentTag.SILVER},
        "cost_gold": 5.0,
        "cost_material": 2.0,
        "stats": EquipmentStats(damage=2.0),
        "special_rules": "Рассеивание: снимает магические баффы с вражеского гекса перед началом рукопашной.",
    },
    HumanAccessoryId.STEEL_BUCKLER_03.value: {
        "id": HumanAccessoryId.STEEL_BUCKLER_03.value,
        "name": "Стальной баклер",
        "lore": "Маленький щит для ближнего боя. Не спасает от стрел, но отлично парирует вражеские клинки.",
        "slot": _SLOT,
        "category": AccessoryCategory.SHIELD,
        "tier": 3,
        "tags": {EquipmentTag.ONE_HANDED},
        "cost_gold": 6.0,
        "cost_material": 4.0,
        "stats": EquipmentStats(
            armor_bonus=4.0,
            initiative_modifier=1,
        ),
    },
    HumanAccessoryId.HEAVY_HERALDIC_SHIELD_04.value: {
        "id": HumanAccessoryId.HEAVY_HERALDIC_SHIELD_04.value,
        "name": "Тяжелый гербовый щит",
        "lore": "Окованные сталью щиты с гербами имперских домов. Символ непоколебимости.",
        "slot": _SLOT,
        "category": AccessoryCategory.SHIELD,
        "tier": 4,
        "tags": {EquipmentTag.ONE_HANDED, EquipmentTag.HEAVY},
        "cost_gold": 8.0,
        "cost_material": 8.0,
        "stats": EquipmentStats(
            armor_bonus=8.0,
            speed_modifier=-0.05,
        ),
        "special_rules": "Стена щитов: если отряд не двигается (стоит в глухой обороне) два хода подряд, лобовой урон снижается на 30%.",
    },
    HumanAccessoryId.TOMES_OF_LITANIES_04.value: {
        "id": HumanAccessoryId.TOMES_OF_LITANIES_04.value,
        "name": "Томы литаний",
        "lore": "Священные тексты, которые жрецы зачитывают прямо посреди кровавой бойни.",
        "slot": _SLOT,
        "category": AccessoryCategory.RELIC,
        "tier": 4,
        "cost_gold": 12.0,
        "cost_material": 5.0,
        "stats": EquipmentStats(),
        "special_rules": "Аура благочестия: пассивно повышает мораль всем союзным отрядам в радиусе 2 гексов.",
    },
    HumanAccessoryId.MEDALLION_OF_PURITY_05.value: {
        "id": HumanAccessoryId.MEDALLION_OF_PURITY_05.value,
        "name": "Медальон абсолютного очищения",
        "lore": "Артефакт, вытягивающий резонит из окружающего пространства, превращая его в безопасный серый пепел.",
        "slot": _SLOT,
        "category": AccessoryCategory.RELIC,
        "tier": 5,
        "tags": {EquipmentTag.SILVER},
        "cost_gold": 20.0,
        "cost_material": 15.0,
        "stats": EquipmentStats(),
        "special_rules": "Зона немоты: блокирует применение любой магии (союзной и вражеской) в радиусе 1 гекса.",
    },
}
