"""
Реестр сборки армий (Ростер) фракции людей.
Объединяет UnitArchetype + Weapon + Armor + Accessory в готовую карточку найма.
"""

from typing import Any

from src.back.gamedata.humans.common import (
    HumanAccessoryId,
    HumanArmorId,
    HumanRosterId,
    HumanUnitId,
    HumanWeaponId,
)

_FACTION = "humans"

ROSTER_LIST: dict[str, dict[str, Any]] = {
    HumanRosterId.ROSTER_BUILDERS.value: {
        "id": HumanRosterId.ROSTER_BUILDERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.BUILDERS_GUILD_00.value,
        "weapon_id": HumanWeaponId.BUILDER_HAMMER_00.value,
        "armor_id": HumanArmorId.WORKER_ROBES_00.value,
        "accessory_id": HumanAccessoryId.FLAMING_TORCHES_00.value,
        "cost_gold": 5.0, # Умножается на количество юнитов в отряде
        "cost_material": 10.0, # Умножается на количество юнитов в отряде
    },
    HumanRosterId.ROSTER_SINNERS.value: {
        "id": HumanRosterId.ROSTER_SINNERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.REPENTANT_SINNERS_00.value,
        "weapon_id": HumanWeaponId.RUSTY_FLAIL_00.value,
        "armor_id": HumanArmorId.HAIRSHIRTS_00.value,
        "accessory_id": None,
        "cost_gold": 0.0,
        "cost_material": 15.0,
    },
    HumanRosterId.ROSTER_MILITIA_CROSSBOWS.value: {
        "id": HumanRosterId.ROSTER_MILITIA_CROSSBOWS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.MILITIA_00.value,
        "weapon_id": HumanWeaponId.IMPERIAL_CROSSBOW_01.value,
        "armor_id": HumanArmorId.WORKER_ROBES_00.value,
        "accessory_id": None,
        "cost_gold": 10.0,
        "cost_material": 10.0,
    },
    HumanRosterId.ROSTER_GUARD_SPEARS.value: {
        "id": HumanRosterId.ROSTER_GUARD_SPEARS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.CITY_GUARD_01.value,
        "weapon_id": HumanWeaponId.INFANTRY_SPEAR_01.value,
        "armor_id": HumanArmorId.PADDED_JACKETS_01.value,
        "accessory_id": None,
        "cost_gold": 25.0,
        "cost_material": 15.0,
    },
    HumanRosterId.ROSTER_HOUNDS.value: {
        "id": HumanRosterId.ROSTER_HOUNDS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.HUNTERS_WITH_DOGS_01.value,
        "weapon_id": HumanWeaponId.SABER_02.value,
        "armor_id": HumanArmorId.LEATHER_BREASTPLATES_01.value,
        "accessory_id": HumanAccessoryId.HUNTING_HORN_01.value,
        "cost_gold": 30.0,
        "cost_material": 10.0,
    },
    HumanRosterId.ROSTER_IRONSIDE_HALBERDIERS.value: {
        "id": HumanRosterId.ROSTER_IRONSIDE_HALBERDIERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.IRONSIDES_02.value,
        "weapon_id": HumanWeaponId.STEEL_HALBERD_02.value,
        "armor_id": HumanArmorId.STEEL_CUIRASSES_02.value,
        "accessory_id": None,
        "cost_gold": 45.0,
        "cost_material": 35.0,
    },
    HumanRosterId.ROSTER_ARQUEBUSIERS.value: {
        "id": HumanRosterId.ROSTER_ARQUEBUSIERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.SHOOTERS_02.value,
        "weapon_id": HumanWeaponId.HEAVY_ARQUEBUS_02.value,
        "armor_id": HumanArmorId.LEATHER_BREASTPLATES_01.value,
        "accessory_id": HumanAccessoryId.POWDER_BANDOLIER_02.value,
        "cost_gold": 50.0,
        "cost_material": 30.0,
    },
    HumanRosterId.ROSTER_LONGBOWMEN.value: {
        "id": HumanRosterId.ROSTER_LONGBOWMEN.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.SHOOTERS_02.value,
        "weapon_id": HumanWeaponId.LONG_BOW_02.value,
        "armor_id": HumanArmorId.PADDED_JACKETS_01.value,
        "accessory_id": HumanAccessoryId.PAVISE_SHIELD_01.value,
        "cost_gold": 40.0,
        "cost_material": 25.0,
    },
    HumanRosterId.ROSTER_FIELD_HOSPITAL.value: {
        "id": HumanRosterId.ROSTER_FIELD_HOSPITAL.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.FIELD_HOSPITAL_02.value,
        "weapon_id": None,
        "armor_id": HumanArmorId.LEATHER_BREASTPLATES_01.value,
        "accessory_id": HumanAccessoryId.SURGICAL_SAWS_02.value,
        "cost_gold": 60.0,
        "cost_material": 10.0,
    },
    HumanRosterId.ROSTER_LIGHT_CAVALRY.value: {
        "id": HumanRosterId.ROSTER_LIGHT_CAVALRY.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.LIGHT_CAVALRY_02.value,
        "weapon_id": HumanWeaponId.SABER_02.value,
        "armor_id": HumanArmorId.CAVALRY_MAIL_02.value,
        "accessory_id": None,
        "cost_gold": 55.0,
        "cost_material": 20.0,
    },
    HumanRosterId.ROSTER_GREATSWORD_VETERANS.value: {
        "id": HumanRosterId.ROSTER_GREATSWORD_VETERANS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.WAR_VETERANS_03.value,
        "weapon_id": HumanWeaponId.FLAMBERGE_03.value,
        "armor_id": HumanArmorId.HEAVY_HALF_PLATE_03.value,
        "accessory_id": None,
        "cost_gold": 80.0,
        "cost_material": 60.0,
    },
    HumanRosterId.ROSTER_WITCH_HUNTERS.value: {
        "id": HumanRosterId.ROSTER_WITCH_HUNTERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.WITCH_HUNTERS_03.value,
        "weapon_id": HumanWeaponId.SILVER_RAPIER_03.value,
        "armor_id": HumanArmorId.PURITY_RUNE_CLOAKS_03.value,
        "accessory_id": HumanAccessoryId.HOLY_WATER_FLASK_03.value,
        "cost_gold": 120.0,
        "cost_material": 30.0,
    },
    HumanRosterId.ROSTER_ORDER_KNIGHTS.value: {
        "id": HumanRosterId.ROSTER_ORDER_KNIGHTS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.KNIGHTS_04.value,
        "weapon_id": HumanWeaponId.KNIGHT_LANCE_04.value,
        "armor_id": HumanArmorId.FULL_KNIGHT_PLATE_04.value,
        "accessory_id": HumanAccessoryId.HEAVY_HERALDIC_SHIELD_04.value,
        "cost_gold": 150.0,
        "cost_material": 120.0,
    },
    HumanRosterId.ROSTER_MAGISTERS.value: {
        "id": HumanRosterId.ROSTER_MAGISTERS.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.INQUISITION_MAGISTERS_05.value,
        "weapon_id": HumanWeaponId.MULTI_BARREL_PISTOL_05.value,
        "armor_id": HumanArmorId.RELIQUARY_ARMOR_05.value,
        "accessory_id": HumanAccessoryId.MEDALLION_OF_PURITY_05.value,
        "cost_gold": 300.0,
        "cost_material": 150.0,
    },
    HumanRosterId.ROSTER_AVATAR.value: {
        "id": HumanRosterId.ROSTER_AVATAR.value,
        "faction_id": _FACTION,
        "unit_archetype_id": HumanUnitId.AVATAR_OF_VENGEANCE_06.value,
        "weapon_id": HumanWeaponId.HOLY_HAMMER_04.value,
        "armor_id": HumanArmorId.RELIQUARY_ARMOR_05.value,
        "accessory_id": HumanAccessoryId.TOMES_OF_LITANIES_04.value,
        "cost_gold": 800.0,
        "cost_material": 400.0,
    },
}
