"""
Реестр аксессуаров фракции зеленокожих.
"""

from typing import Any

from src.back.l01_domain.army.constants import (
    AccessoryCategory,
    EquipmentSlot,
    EquipmentTag,
)
from src.back.l01_domain.army.models.card.equipment import EquipmentStats
from src.back.gamedata.greenskins.common import GreenskinsAccessoryId

_SLOT = EquipmentSlot.ACCESSORY

ACCESSORIES_LIST: dict[str, dict[str, Any]] = {
    GreenskinsAccessoryId.NAILED_PLANK_00.value: {
        "id": GreenskinsAccessoryId.NAILED_PLANK_00.value,
        "name": "Доска с гвоздями",
        "lore": "Используется и как хреновый щит, и как оружие, чтобы бить по лицу. Дешево и жестоко.",
        "slot": _SLOT,
        "category": AccessoryCategory.SHIELD,
        "tier": 0,
        "tags": {EquipmentTag.ONE_HANDED},
        "cost_gold": 0.0,
        "cost_material": 1.0,
        "stats": EquipmentStats(armor_bonus=1.0, damage=1.0),
    },
    GreenskinsAccessoryId.ROTTEN_MUSHROOMS_00.value: {
        "id": GreenskinsAccessoryId.ROTTEN_MUSHROOMS_00.value,
        "name": "Горсть гнилых грибов",
        "lore": "Гоблины жуют их перед боем, чтобы не чувствовать страха и боли. Главное не переборщить, иначе желудок лопнет.",
        "slot": _SLOT,
        "category": AccessoryCategory.POTION,
        "tier": 0,
        "cost_gold": 0.5,
        "cost_material": 0.0,
        "stats": EquipmentStats(initiative_modifier=1),
        "special_rules": "Временное обезболивание: дает временный бонус к морали на старте боя.",
    },
    GreenskinsAccessoryId.STOLEN_TOWER_SHIELD_01.value: {
        "id": GreenskinsAccessoryId.STOLEN_TOWER_SHIELD_01.value,
        "name": "Украденный ростовой щит",
        "lore": "Оторван от телеги или снят с трупа имперского арбалетчика. Слишком тяжелый, но отлично закрывает тушу.",
        "slot": _SLOT,
        "category": AccessoryCategory.SHIELD,
        "tier": 1,
        "tags": {EquipmentTag.ONE_HANDED, EquipmentTag.HEAVY},
        "cost_gold": 1.0,
        "cost_material": 2.0,
        "stats": EquipmentStats(armor_bonus=3.0, speed_modifier=-0.05),
    },
    GreenskinsAccessoryId.SCAVENGER_NET_01.value: {
        "id": GreenskinsAccessoryId.SCAVENGER_NET_01.value,
        "name": "Сеть мародеров",
        "lore": "Рыболовные и охотничьи сети с грузилами. В начале боя орки накидывают их на головы врагам.",
        "slot": _SLOT,
        "category": AccessoryCategory.TRAP,
        "tier": 1,
        "cost_gold": 1.0,
        "cost_material": 1.5,
        "stats": EquipmentStats(initiative_modifier=2),
        "special_rules": "Запутывание: снижает инициативу вражеского отряда в первый ход ближнего боя.",
    },
    GreenskinsAccessoryId.OFFHAND_AXE_01.value: {
        "id": GreenskinsAccessoryId.OFFHAND_AXE_01.value,
        "name": "Дополнительный топор",
        "lore": "Почему бы не взять по топору в каждую руку? Больше топоров — больше крови!",
        "slot": _SLOT,
        "category": AccessoryCategory.MISC,
        "tier": 1,
        "tags": {EquipmentTag.ONE_HANDED},
        "cost_gold": 1.0,
        "cost_material": 2.0,
        "stats": EquipmentStats(damage=4.0),
    },
    GreenskinsAccessoryId.TRIBAL_DRUM_02.value: {
        "id": GreenskinsAccessoryId.TRIBAL_DRUM_02.value,
        "name": "Барабан племени",
        "lore": "Барабан, натянутый из кожи поверженных врагов. Ритм заставляет орков впадать в кровавый раж.",
        "slot": _SLOT,
        "category": AccessoryCategory.INSTRUMENT,
        "tier": 2,
        "cost_gold": 2.0,
        "cost_material": 3.0,
        "stats": EquipmentStats(),
        "special_rules": "Ритм Орды: пассивно увеличивает скорость восстановления выносливости для союзных орков в радиусе 1 гекса.",
    },
    GreenskinsAccessoryId.RED_AMANITAS_02.value: {
        "id": GreenskinsAccessoryId.RED_AMANITAS_02.value,
        "name": "Связка 'Красных мухоморов'",
        "lore": "Особый сорт ядовитых грибов, выращенных в темноте. Орка от них 'штырит' так, что он крутится на месте как волчок.",
        "slot": _SLOT,
        "category": AccessoryCategory.POTION,
        "tier": 2,
        "cost_gold": 3.0,
        "cost_material": 1.0,
        "stats": EquipmentStats(
            damage=3.0,
            initiative_modifier=3,
        ),
        "special_rules": "Боевой транс: игнорирует эффекты страха, но каждый такт боя отряд теряет небольшое количество здоровья от отравления.",
    },
    GreenskinsAccessoryId.GLASS_SCOPE_03.value: {
        "id": GreenskinsAccessoryId.GLASS_SCOPE_03.value,
        "name": "Стекляшка-прицел",
        "lore": "Гоблины-снайперы приматывают к своим мушкетам куски бутылочного стекла и подзорных труб. Удивительно, но они начинают попадать.",
        "slot": _SLOT,
        "category": AccessoryCategory.MISC,
        "tier": 3,
        "cost_gold": 4.0,
        "cost_material": 2.0,
        "stats": EquipmentStats(range_hexes=1),
        "special_rules": "Точный глаз: снимает врожденный штраф на косоглазие и осечки у гоблинских стрелков.",
    },
    GreenskinsAccessoryId.AMULET_OF_MADNESS_03.value: {
        "id": GreenskinsAccessoryId.AMULET_OF_MADNESS_03.value,
        "name": "Амулет безумия",
        "lore": "Череп мелкого мутанта, заполненный светящимся резонитом. Излучает энергию, которая заставляет врагов галлюцинировать.",
        "slot": _SLOT,
        "category": AccessoryCategory.RELIC,
        "tier": 3,
        "tags": {EquipmentTag.RESONITE_POWERED},
        "cost_gold": 5.0,
        "cost_material": 6.0,
        "stats": EquipmentStats(armor_bonus=2.0),
        "special_rules": "Шизофрения: накладывает штраф к морали на любой вражеский отряд, вступивший в ближний бой с носителем.",
    },
    GreenskinsAccessoryId.BUNGEE_WINCH_03.value: {
        "id": GreenskinsAccessoryId.BUNGEE_WINCH_03.value,
        "name": "Лебедка с резинкой",
        "lore": "Гоблинское изобретение. Жгут из кишок монстра натягивается лебедкой... и запускает самих гоблинов в воздух!",
        "slot": _SLOT,
        "category": AccessoryCategory.MISC,
        "tier": 3,
        "cost_gold": 6.0,
        "cost_material": 8.0,
        "stats": EquipmentStats(range_hexes=3),
        "special_rules": "Запуск десанта: позволяет отряду 'перепрыгнуть' через препятствия или союзников на расстояние до 3 гексов. Приземление отнимает у отряда 10% здоровья.",
    },
    GreenskinsAccessoryId.BASKET_SPOTTER_04.value: {
        "id": GreenskinsAccessoryId.BASKET_SPOTTER_04.value,
        "name": "Гоблин-наводчик в корзине",
        "lore": "Глупый, но глазастый гоблин сидит в плетеной корзине, привязанной к спине огра, и орет, куда тому бить.",
        "slot": _SLOT,
        "category": AccessoryCategory.MISC,
        "tier": 4,
        "cost_gold": 8.0,
        "cost_material": 5.0,
        "stats": EquipmentStats(initiative_modifier=5),
        "special_rules": "Смотри туда!: снимает штрафы на фланговые атаки, огр быстрее реагирует на смену позиции врага.",
    },
}
