"""
Реестр базовых архетипов юнитов фракции людей.
"""

from typing import Any

from src.back.l01_domain.army.constants import UnitSizeCategory
from src.back.l01_domain.army.models.card.unit import BaseUnitStats
from src.back.l01_domain.common import FactionRace
from src.back.gamedata.humans.common import HumanUnitId

_RACE = FactionRace.HUMANS
_FACTION = "humans"

UNITS_LIST: dict[str, dict[str, Any]] = {
    HumanUnitId.BUILDERS_GUILD_00.value: {
        "id": HumanUnitId.BUILDERS_GUILD_00.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Гильдия строителей",
        "tier": 0,
        "default_unit_count": 100,
        "base_stats": BaseUnitStats(
            max_hp=12.0,
            base_speed=2.0,
            base_morale=45.0,
            base_initiative=8,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 1.0,
        "base_upkeep_gold": 0.1,
        "lore_description": "Обычные рабочие, возводящие стены и баррикады. Медленно бьют молотками в бою, но отлично работают лопатами.",
    },
    HumanUnitId.REPENTANT_SINNERS_00.value: {
        "id": HumanUnitId.REPENTANT_SINNERS_00.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Кающиеся грешники",
        "tier": 0,
        "default_unit_count": 180,
        "base_stats": BaseUnitStats(
            max_hp=15.0,
            base_speed=2.5,
            base_morale=100.0,  # Игнорируют страх из-за экстаза
            base_initiative=12,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 0.5,  # Питаются отбросами и верой
        "base_upkeep_gold": 0.0,
        "lore_description": "Толпа фанатиков в рубищах. Они ищут искупления через боль и смерть в бою с мутантами.",
    },
    HumanUnitId.MILITIA_00.value: {
        "id": HumanUnitId.MILITIA_00.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Ополченцы",
        "tier": 0,
        "default_unit_count": 100,
        "base_stats": BaseUnitStats(
            max_hp=15.0,
            base_speed=2.0,
            base_morale=40.0,
            base_initiative=9,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 1.0,
        "base_upkeep_gold": 0.2,
        "lore_description": "Вчерашние крестьяне, которым дали в руки арбалеты или вилы. Быстро разбегаются, если до них добирается враг.",
    },
    HumanUnitId.CITY_GUARD_01.value: {
        "id": HumanUnitId.CITY_GUARD_01.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Городская стража",
        "tier": 1,
        "default_unit_count": 120,
        "base_stats": BaseUnitStats(
            max_hp=20.0,
            base_speed=2.0,
            base_morale=60.0,
            base_initiative=10,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 1.0,
        "base_upkeep_gold": 0.5,
        "lore_description": "Дисциплинированная основа обороны любого имперского поселения. Привыкли держать строй.",
    },
    HumanUnitId.HUNTERS_WITH_DOGS_01.value: {
        "id": HumanUnitId.HUNTERS_WITH_DOGS_01.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Егеря с боевыми псами",
        "tier": 1,
        "default_unit_count": 100,  # 20 людей + 80 псов (балансно считаем как один отряд)
        "base_stats": BaseUnitStats(
            max_hp=18.0,
            base_speed=3.0,
            base_morale=55.0,
            base_initiative=14,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 1.5,  # Собаки много едят
        "base_upkeep_gold": 0.5,
        "lore_description": "Быстрые своры, натасканные загонять отступающих и вырезать лучников.",
    },
    HumanUnitId.IRONSIDES_02.value: {
        "id": HumanUnitId.IRONSIDES_02.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Железнобокие",
        "tier": 2,
        "default_unit_count": 80,
        "base_stats": BaseUnitStats(
            max_hp=25.0,
            base_armor=1.0,
            base_speed=2.0,
            base_morale=70.0,
            base_initiative=10,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 1.0,
        "base_upkeep_gold": 1.0,
        "lore_description": "Регулярная тяжелая пехота. Уничтожители крупных целей, не ведающие страха перед конницей.",
    },
    HumanUnitId.SHOOTERS_02.value: {
        "id": HumanUnitId.SHOOTERS_02.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Стрелковые роты",
        "tier": 2,
        "default_unit_count": 60,
        "base_stats": BaseUnitStats(
            max_hp=20.0,
            base_speed=2.0,
            base_morale=65.0,
            base_initiative=11,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 1.0,
        "base_upkeep_gold": 1.0,
        "lore_description": "Специалисты дальнего боя Империи. Годами тренируются обращаться с порохом или тяжелыми луками.",
    },
    HumanUnitId.FIELD_HOSPITAL_02.value: {
        "id": HumanUnitId.FIELD_HOSPITAL_02.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Полевой госпиталь",
        "tier": 2,
        "default_unit_count": 3,
        "base_stats": BaseUnitStats(
            max_hp=30.0,
            base_speed=1.5,
            base_morale=50.0,
            base_initiative=5,
            size_category=UnitSizeCategory.LARGE,  # Палатки и телеги
        ),
        "base_upkeep_food": 2.0,
        "base_upkeep_gold": 2.0,
        "lore_description": "Санитары и лекари. На поле боя не сражаются, но их присутствие снижает безвозвратные потери среди солдат.",
    },
    HumanUnitId.LIGHT_CAVALRY_02.value: {
        "id": HumanUnitId.LIGHT_CAVALRY_02.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Легкая кавалерия",
        "tier": 2,
        "default_unit_count": 60,
        "base_stats": BaseUnitStats(
            max_hp=30.0,
            base_speed=4.0,
            base_morale=60.0,
            base_initiative=15,
            size_category=UnitSizeCategory.LARGE,
        ),
        "base_upkeep_food": 2.0,
        "base_upkeep_gold": 1.5,
        "lore_description": "Быстрые конные разведчики. Идеальны для фланговых маневров и преследования.",
    },
    HumanUnitId.WAR_VETERANS_03.value: {
        "id": HumanUnitId.WAR_VETERANS_03.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Ветераны Империи",
        "tier": 3,
        "default_unit_count": 50,
        "base_stats": BaseUnitStats(
            max_hp=35.0,
            base_armor=1.0,
            base_speed=2.0,
            base_morale=85.0,
            base_initiative=12,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 1.0,
        "base_upkeep_gold": 2.0,
        "lore_description": "Солдаты, пережившие десятки сражений. Закованы в сталь, бьют тяжело и точно.",
    },
    HumanUnitId.WITCH_HUNTERS_03.value: {
        "id": HumanUnitId.WITCH_HUNTERS_03.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Охотники на ведьм",
        "tier": 3,
        "default_unit_count": 15,
        "base_stats": BaseUnitStats(
            max_hp=40.0,
            base_speed=2.5,
            base_morale=90.0,
            base_initiative=16,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 1.0,
        "base_upkeep_gold": 3.0,
        "lore_description": "Дуэлянты Инквизиции. Профессиональные убийцы всего, что связано с магией и мутациями.",
    },
    HumanUnitId.KNIGHTS_04.value: {
        "id": HumanUnitId.KNIGHTS_04.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Орденские рыцари",
        "tier": 4,
        "default_unit_count": 30,
        "base_stats": BaseUnitStats(
            max_hp=55.0,
            base_armor=2.0,
            base_speed=3.5,
            base_morale=95.0,
            base_stamina=100.0,
            base_initiative=12,
            size_category=UnitSizeCategory.LARGE,
        ),
        "base_upkeep_food": 3.0,
        "base_upkeep_gold": 5.0,
        "lore_description": "Бронированные танки Империи. Их сокрушительный натиск способен пробить любой пехотный строй.",
    },
    HumanUnitId.INQUISITION_MAGISTERS_05.value: {
        "id": HumanUnitId.INQUISITION_MAGISTERS_05.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Магистры Инквизиции",
        "tier": 5,
        "default_unit_count": 5,
        "base_stats": BaseUnitStats(
            max_hp=80.0,
            base_armor=3.0,
            base_speed=2.0,
            base_morale=100.0,
            base_stamina=100.0,
            base_initiative=18,
            size_category=UnitSizeCategory.MEDIUM,
        ),
        "base_upkeep_food": 1.0,
        "base_upkeep_gold": 10.0,
        "lore_description": "Элита Зала Инквизиции. Внушают ужас одним своим присутствием, блокируя проявления вражеской магии.",
    },
    HumanUnitId.AVATAR_OF_VENGEANCE_06.value: {
        "id": HumanUnitId.AVATAR_OF_VENGEANCE_06.value,
        "race": _RACE,
        "faction_id": _FACTION,
        "name": "Воплощение Мщения",
        "tier": 6,
        "default_unit_count": 1,
        "base_stats": BaseUnitStats(
            max_hp=600.0,
            base_armor=10.0,
            base_speed=3.0,
            base_morale=100.0,
            base_stamina=100.0,
            base_initiative=20,
            size_category=UnitSizeCategory.HUGE,
        ),
        "base_upkeep_food": 0.0,
        "base_upkeep_gold": 50.0,
        "lore_description": "Ультимативное оружие Цитадели. Механико-религиозный колосс, левитирующий над землей и уничтожающий ересь.",
    },
}
